package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"fmt"

	"github.com/yangguang/Twilight/UniQuery/graph/generated"
	"github.com/yangguang/Twilight/UniQuery/models"
)

// Account is the resolver for the account field.
func (r *queryResolver) Account(ctx context.Context, id string) (*models.Account, error) {
	panic(fmt.Errorf("not implemented: Account - account"))
}

// Accounts is the resolver for the accounts field.
func (r *queryResolver) Accounts(ctx context.Context, page *int, limit *int) ([]*models.Account, error) {
	panic(fmt.Errorf("not implemented: Accounts - accounts"))
}

// AccountTransferEvents is the resolver for the accountTransferEvents field.
func (r *queryResolver) AccountTransferEvents(ctx context.Context, accountID string, page *int, limit *int, buyOrSell *string, sortBy *string) ([]*models.AccountTransferEvent, error) {
	panic(fmt.Errorf("not implemented: AccountTransferEvents - accountTransferEvents"))
}

// AccountTransferHistory is the resolver for the accountTransferHistory field.
func (r *queryResolver) AccountTransferHistory(ctx context.Context, accountID string, page *int, limit *int, buyOrSell *string, sortBy *string) ([]*models.AccountTransferHistory, error) {
	panic(fmt.Errorf("not implemented: AccountTransferHistory - accountTransferHistory"))
}

// Token is the resolver for the token field.
func (r *queryResolver) Token(ctx context.Context, id string) (*models.Token, error) {
	panic(fmt.Errorf("not implemented: Token - token"))
}

// Tokens is the resolver for the tokens field.
func (r *queryResolver) Tokens(ctx context.Context, page *int, limit *int, sortBy *string) ([]*models.Token, error) {
	panic(fmt.Errorf("not implemented: Tokens - tokens"))
}

// TokenTransferEvents is the resolver for the tokenTransferEvents field.
func (r *queryResolver) TokenTransferEvents(ctx context.Context, tokenID string, page *int, limit *int, buyOrSell *string, onlySmartMoney *bool, onlyWithCex *bool, onlyWithDex *bool, sortBy *string) ([]*models.TokenTransferEvent, error) {
	panic(fmt.Errorf("not implemented: TokenTransferEvents - tokenTransferEvents"))
}

// TokenHolders is the resolver for the tokenHolders field.
func (r *queryResolver) TokenHolders(ctx context.Context, tokenID string, page *int, limit *int, sortBy *string) ([]*models.TokenHolder, error) {
	panic(fmt.Errorf("not implemented: TokenHolders - tokenHolders"))
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
