kafka:
  brokers:
    - localhost:9092
  topics:
    chain_transactions_new: chain_transactions_new
  consumer:
    poll_timeout_ms: 1000
    max_poll_records: 500
    session_timeout_ms: 30000
    heartbeat_interval_ms: 10000

postgres:
  host: localhost
  port: 5432
  user: twilight
  password: twilight123
  database: twilight
  sslmode: disable
  pool:
    max_connections: 20
    min_connections: 5
    max_idle_time_seconds: 300

chain:
  rpc_url: http://127.0.0.1:8545  # Local Hardhat node
  chain_id: 31337  # Hardhat default chain ID
  block_time_ms: 2000  # Target block time in milliseconds
  polling:
    interval_ms: 1000  # Block polling interval
    max_blocks_per_poll: 10  # Maximum blocks to process in one poll
    retry_interval_ms: 3000  # Retry interval on error
  confirmation:
    required_blocks: 1  # Number of block confirmations required
    timeout_ms: 30000  # Transaction confirmation timeout

services:
  listener:
    port: 8080
    batch_size: 100  # Number of transactions to process in batch
    worker_threads: 4  # Number of worker threads
    queue_capacity: 1000  # Internal queue capacity
  strategy:
    port: 8081
    update_interval_ms: 5000  # Strategy update interval
  datamanager:
    port: 8082
    cache_size: 1000  # Size of in-memory cache
    cleanup_interval_ms: 300000  # Cache cleanup interval

flink:
  jobmanager_url: http://localhost:8081
  checkpoint:
    interval_ms: 10000  # Checkpoint interval
    timeout_ms: 60000  # Checkpoint timeout
    min_pause_ms: 5000  # Minimum pause between checkpoints
  window:
    size_ms: 60000  # Window size for aggregations
    slide_ms: 10000  # Window slide interval
  watermark:
    delay_ms: 5000  # Maximum out-of-orderness
  parallelism: 2  # Default parallelism for Flink jobs 